import { execFileSync } from 'node:child_process';
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import * as path from 'node:path';
import { apiDir, stageDir } from './paths.mjs';

/**
 * Build apps/desktop/build/server: a self-contained production copy of the API.
 *
 * It cannot simply point at apps/api/node_modules. pnpm lays that out as
 * symlinks into .pnpm/, which electron-builder does not reliably dereference
 * when copying and which @electron/rebuild mishandles when walking. So we do
 * what the Dockerfile's runner stage already does and is proven to work for
 * these native modules: a fresh npm install into a real directory tree.
 */

function step(message) {
  console.log(`[stage] ${message}`);
}

function assert(condition, message) {
  if (!condition) {
    console.error(`[stage] ERROR: ${message}`);
    process.exit(1);
  }
}

step(`Staging API into ${stageDir}`);
rmSync(stageDir, { recursive: true, force: true });
mkdirSync(stageDir, { recursive: true });

// 1. Compiled server.
const apiDist = path.join(apiDir, 'dist');
assert(existsSync(apiDist), `apps/api/dist is missing. Run "pnpm -F api build" first.`);
cpSync(apiDist, path.join(stageDir, 'dist'), { recursive: true });

// nest build emits dist/src/main.js, not dist/main.js: prisma.config.ts sits at
// the api package root and is included in the TypeScript build, which shifts the
// inferred rootDir. run.sh depends on the same path. If a future tsconfig change
// moves it, fail here rather than shipping an app that cannot start.
const serverEntry = path.join(stageDir, 'dist', 'src', 'main.js');
assert(
  existsSync(serverEntry),
  `Expected the server entry point at dist/src/main.js. Found neither it nor an obvious alternative.`,
);

// 2. Generated Prisma client. nest-cli.json copies src/generated into dist/src
//    as a build asset; copy it directly as a fallback, as the Dockerfile does.
const generatedInDist = path.join(stageDir, 'dist', 'src', 'generated');
if (!existsSync(generatedInDist)) {
  step('dist/src/generated was missing; copying it from src/');
  cpSync(path.join(apiDir, 'src', 'generated'), generatedInDist, { recursive: true });
}
assert(existsSync(generatedInDist), 'The generated Prisma client is missing from the staged tree.');

// 3. Prisma schema. The desktop app runs `prisma db push` at launch, exactly as
//    run.sh does in the add-on container.
mkdirSync(path.join(stageDir, 'prisma'), { recursive: true });
cpSync(path.join(apiDir, 'prisma', 'schema.prisma'), path.join(stageDir, 'prisma', 'schema.prisma'));

// 4. Prisma config. schema.prisma's datasource block has no url, so the CLI
//    needs a config file to supply one. apps/api/prisma.config.ts is TypeScript
//    and would need a loader inside the packaged app, so emit plain CommonJS
//    with the same behaviour instead.
writeFileSync(
  path.join(stageDir, 'prisma.config.js'),
  `// Generated by apps/desktop/scripts/stage-server.mjs — do not edit.
// Mirrors apps/api/prisma.config.ts without the TypeScript loader.
const { defineConfig } = require('@prisma/config');

function getDatabaseUrl() {
  let url = process.env.DATABASE_URL;
  if (!url) throw new Error('DATABASE_URL is not set');
  if (!url.startsWith('file:')) url = \`file:\${url}\`;
  return url;
}

module.exports = defineConfig({ datasource: { url: getDatabaseUrl() } });
`,
  'utf8',
);

// 5. Trimmed production manifest.
const pkg = JSON.parse(readFileSync(path.join(apiDir, 'package.json'), 'utf8'));
const dependencies = { ...pkg.dependencies };

writeFileSync(
  path.join(stageDir, 'package.json'),
  `${JSON.stringify(
    {
      name: 'priperfin-server',
      version: '0.0.0',
      private: true,
      // Dropping "scripts" entirely is what stops postinstall (prisma generate)
      // from running: the generated client is copied in above, already built.
      dependencies,
    },
    null,
    2,
  )}\n`,
  'utf8',
);

// 6. Production install into real directories.
//    --legacy-peer-deps because prisma declares better-sqlite3 as a peer; the
//    Dockerfile uses the same flag for the same reason.
step('Installing production dependencies (this compiles native modules)');
execFileSync(
  'npm',
  ['install', '--omit=dev', '--omit=optional', '--legacy-peer-deps', '--no-audit', '--no-fund'],
  { cwd: stageDir, stdio: 'inherit', shell: process.platform === 'win32' },
);

// 7. Resolution checks that only fail at runtime on a packaged build.
//    The generated client does a bare require("@prisma/client-runtime-utils"),
//    which arrives transitively via @prisma/client.
for (const [label, relative] of [
  ['@prisma/client-runtime-utils', path.join('node_modules', '@prisma', 'client-runtime-utils')],
  ['better-sqlite3', path.join('node_modules', 'better-sqlite3')],
  ['bcrypt', path.join('node_modules', 'bcrypt')],
  ['prisma CLI', path.join('node_modules', 'prisma', 'build', 'index.js')],
]) {
  assert(existsSync(path.join(stageDir, relative)), `${label} is missing from the staged tree (${relative}).`);
}

step('Staged server is ready');
